reactcom-frontend:
  build: ./frontend
  ports:
    - "8060:3000"
  volumes:
    - ./frontend:/usr/src/app

# Magento 2
reactcom-magento2-app:
  build: ./docker/magento2-nginx
  links:
    - reactcom-magento2-phpfpm
    - reactcom-magento2-db
  volumes_from:
    - reactcom-magento2-appdata
  ports:
    - 8061:80

reactcom-magento2-appdata:
  image: tianon/true
  volumes:
    - /var/www/html
    - ~/.composer:/var/www/.composer
    - ./backend:/var/www/html

reactcom-magento2-phpfpm:
  build: ./docker/magento2-phpfpm
  links:
    - reactcom-magento2-db
  volumes_from:
    - reactcom-magento2-appdata
  env_file: ./docker/env/setup.env
  environment:
    - M2SETUP_VERSION=2.1.5

reactcom-magento2-db:
  image: percona:5.7
  volumes_from:
    - reactcom-magento2-dbdata
  ports:
    - 8001:3306
  env_file: ./docker/env/mysql.env

reactcom-magento2-dbdata:
  image: tianon/true
  volumes:
    - /var/lib/mysql

reactcom-magento2-setup:
  build: docker/magento2-phpfpm
  command: /usr/local/bin/mage-setup
  links:
    - reactcom-magento2-db
  volumes_from:
    - reactcom-magento2-appdata
  env_file: ./docker/env/setup.env
  environment:
    - M2SETUP_VERSION=2.1.5
